outputs current local weather
ThetaTauSBU/OT_mascot_robot pull request #25
Opened 2020-10-31 17:49 UTC by jahnaviarora00

# Summary
Script that outputs the current local weather (description, temp, humidity, pressure etc.) for a current city. 
Need to install requests (sudo pip install requests)

# Test Plan
Reviewer can change city to test code. 

# Test Data
tested with multiple cities
ex. 
input - Stony Brook 
output - 
City: Stony Brook
Temperature (F): 39.26
Humidity: 45
Pressure: 1034
Weather Report: few clouds

input - Syosset
output - 
City: Syosset
Temperature (F): 39.6
Humidity: 52
Pressure: 1034
Weather Report: clear sky

2020-11-01 23:02 UTC, SeannZhou approved these changes

2020-11-02 09:20 UTC, gammaseeker commented on scripts/LCD-007.py
> +import requests, json
Add new line after import statement

2020-11-02 09:21 UTC, gammaseeker commented on scripts/LCD-007.py
> +URL = BASE + "q="+ CITY + "&appid=" + APIKEY
Add new line after constant declarations

2020-11-02 09:21 UTC, gammaseeker commented on scripts/LCD-007.py
> +    print("Error in the HTTP Request")
Add a new line at the end of the file, it seems like github is complaining about it.

2020-11-02 09:23 UTC, gammaseeker requested changes
Instead of `LCD-007.py` let's rename your file to `get_weather.py` to make it more descriptive. Everything else looks good other than some nit picky styling changes.

2020-11-02 09:25 UTC, gammaseeker commented on scripts/LCD-007.py
> +import requests, json
Add shebang line before import statement `#!/usr/bin/python3`
This way voicecommand can simply invoke your script without having to call `python3`

2020-11-02 16:36 UTC, gammaseeker commented on scripts/LCD-007.py
> +APIKEY = "fc2822e01a0efcce52cb56212fe44fd5"
General comment, you don't need to take action on this. It is bad practice to put API keys in the code. Let's say you are working with sensitive data or have a certain quota to the amt of times you can send a request to an API. If I can see your API key in the code I can grief your program and abuse your credentials to hit that quota. As a result of hitting that quota, I render your service useless bc you can't use that API anymore. 

The canonical way to handle this problem is to have a hidden `.env` file somewhere that stores all your API keys and other credentials. You'd have your script read from this `.env` file and store your credentials in some constant so nobody can know your API key.

2020-11-02 21:51 UTC, closed without merging