[LCD-009] Added current localtime script
ThetaTauSBU/OT_mascot_robot pull request #30
Opened 2020-11-03 05:01 UTC by yewnikmtham

# Summary
Script that outputs the local time in the 12-hour clock format.

# Test Plan
There are no inputs; just run it.

# Test Data
Example output: It is 12:01 AM

2020-11-03 16:40 UTC, gammaseeker commented on scripts/get_localtime.py
> +import time
Add shebang line before import statement `#!/usr/bin/python3`
This way voicecommand can simply invoke your script without having to call python3

2020-11-03 16:40 UTC, gammaseeker commented on scripts/get_localtime.py
> +print("It is", current_time)
Add a new line at the end of the file, it seems like github is complaining about it.

2020-11-03 16:40 UTC, gammaseeker requested changes
Looks good, minor styling changes requested.

2020-11-09 18:16 UTC, gammaseeker approved these changes
Great work! Thank you.

2020-11-09 21:45 UTC, SeannZhou approved these changes

2020-11-09 23:11 UTC, merged